@baseUrl = tradingview.sukruuzel.com
@contentType = application/json
@passphrase = suzel
@exchange = BINANCE
@ticker = BATUSDT
@position = 30.39

###

# @name Buy

POST https://{{baseUrl}}/webhook HTTP/1.1
Content-Type: {{contentType}}

{
  "passphrase": "{{passphrase}}",
  "time": "{{$timestamp}}",
  "exchange": "{{exchange}}",
  "ticker": "{{ticker}}",
  "bar": {
    "time": "{{$timestamp}}",
    "open": 0.0,
    "high": 0.0,
    "low": 0.0,
    "close": 0.0,
    "volume": 0
  },
  "strategy": {
    "position_size": {{position}},
    "order_action": "buy",
    "order_contracts": 1,
    "order_price": 0.0,
    "order_id": "",
    "order_comment": "",
    "order_alert_message": "",
    "market_position": "",
    "market_position_size": 0,
    "prev_market_position": "",
    "prev_market_position_size": 0
  }
}

###

# @name Sell

POST https://{{baseUrl}}/webhook HTTP/1.1
Content-Type: {{contentType}}

{
  "passphrase": "{{passphrase}}",
  "time": "{{$timestamp}}",
  "exchange": "{{exchange}}",
  "ticker": "{{ticker}}",
  "bar": {
    "time": "{{$timestamp}}",
    "open": 0.0,
    "high": 0.0,
    "low": 0.0,
    "close": 0.0,
    "volume": 0
  },
  "strategy": {
    "position_size": {{position}},
    "order_action": "sell",
    "order_contracts": 1,
    "order_price": 0.0,
    "order_id": "",
    "order_comment": "",
    "order_alert_message": "",
    "market_position": "",
    "market_position_size": 0,
    "prev_market_position": "",
    "prev_market_position_size": 0
  }
}
