@baseUrl = tradingview.sukruuzel.com
@contentType = application/json
@passphrase = suzel
@ticker = UNIUSDT

###

# @name buy

POST https://{{baseUrl}}/webhook HTTP/1.1
Content-Type: {{contentType}}

{
  "passphrase": "{{passphrase}}",
  "time": "{{$timestamp}}",
  "exchange": "BINANCE",
  "side": "buy",
  "ticker": "{{ticker}}",
  "price": 15
}

###

# @name sell

POST https://{{baseUrl}}/webhook HTTP/1.1
Content-Type: {{contentType}}

{
  "passphrase": "{{passphrase}}",
  "time": "{{$timestamp}}",
  "exchange": "BINANCE",
  "side": "sell",
  "ticker": "{{ticker}}"
}
