@baseUrl = tradingview.sukruuzel.com
@contentType = application/json
@passphrase = suzel
@exchange = BINANCE
@ticker = UNIUSDT
@position = 15

###

# @name buy

POST https://{{baseUrl}}/webhook HTTP/1.1
Content-Type: {{contentType}}

{
  "passphrase": "{{passphrase}}",
  "time": "{{$timestamp}}",
  "exchange": "{{exchange}}",
  "ticker": "{{ticker}}",
  "bar": {
    "time": "{{$timestamp}}",
    "open": 0.002748,
    "high": 0.0027486,
    "low": 0.002748,
    "close": 0.0027486,
    "volume": 150177
  },
  "strategy": {
    "position_size": {{position}},
    "order_action": "buy",
    "order_contracts": {{position}},
    "order_price": 0.0027451,
    "order_id": "doge door",
    "market_position": "long",
    "market_position_size": {{position}},
    "prev_market_position": "flat",
    "prev_market_position_size": 0
  }
}

###

# @name sell

POST https://{{baseUrl}}/webhook HTTP/1.1
Content-Type: {{contentType}}

{
  "passphrase": "{{passphrase}}",
  "time": "{{$timestamp}}",
  "exchange": "{{exchange}}",
  "ticker": "{{ticker}}",
  "bar": {
    "time": "{{$timestamp}}",
    "open": 0.002748,
    "high": 0.0027486,
    "low": 0.002748,
    "close": 0.0027486,
    "volume": 150177
  },
  "strategy": {
    "position_size": {{position}},
    "order_action": "sell",
    "order_contracts": {{position}},
    "order_price": 0.0027451,
    "order_id": "doge door",
    "market_position": "long",
    "market_position_size": {{position}},
    "prev_market_position": "flat",
    "prev_market_position_size": 0
  }
}
