//@version=5
// RSI Strategy v1.0
// Created by Suzel
// www.sukruuzel.com

strategy(title="RSI Strategy TEST",
         initial_capital=50,
         default_qty_value=100,
         default_qty_type=strategy.percent_of_equity,
         format=format.price,
         precision=2,
         overlay=true)

// Get user input
rsiSource = input.source(title="RSI Source", defval=close)
rsiLength = input.int(title="RSI Length", defval=14)
rsiOverbought = input.int(title="RSI Overbought Level", defval=70)
rsiOversold = input.int(title="RSI Oversold Level", defval=30)

// Get RSI value
rsiValue = ta.rsi(rsiSource, rsiLength)
rsiOB = rsiValue >= rsiOverbought
rsiOS = rsiValue <= rsiOversold

// Identify engulfing candles
bullishEC = close > open[1] and close[1] < open[1]
bearishEC = close < open[1] and close[1] > open[1]
tradeSignal = ((rsiOS or rsiOS[1]) and bullishEC) or ((rsiOB or rsiOB[1]) and bearishEC)

// Execute trade if condition is True
strategy.entry("long", strategy.long, 100, when=tradeSignal and bullishEC)
strategy.close("long", when=tradeSignal and bearishEC)

// Plot signals to chart
plotshape(tradeSignal and bullishEC, title="Long", location=location.belowbar, color=color.green, style=shape.triangleup, text="Long")
plotshape(tradeSignal and bearishEC, title="Short", location=location.abovebar, color=color.red, style=shape.triangledown, text="Short")
