//@version=4
strategy("My Strategy", overlay=true, margin_long=100, margin_short=100)


long_tp_inp = input(100, title="Long Take Profit %", step=0.1) / 100
price = strategy.position_avg_price * (1 + long_tp_inp)
plot(price)


if bar_index == 1
    strategy.entry ("LONG", true)

strategy.exit("EXIT", "LONG", limit =   price)

//-----------------------------------------------------------------------------

// Execute trade if condition is True
// if (longCondition)
//     stopLoss = low - atr * 2
//     takeProfit = high + atr * 2
//     strategy.entry("long", strategy.long, 100, when = rsi > 50)
//     strategy.exit("exit", "long", stop=stopLoss, limit=takeProfit)

// if (shortCondition)
//     stopLoss = high + atr * 2
//     takeProfit = low - atr * 2
//     strategy.entry("short", strategy.short, 100, when = rsi < 50)
//     strategy.exit("exit", "short", stop=stopLoss, limit=takeProfit)

//-----------------------------------------------------------------------------

start_date = input(title="Start Date", type=input.integer, defval=4, minval=1, maxval=31)
start_month = input(title="Start Month", type=input.integer, defval=9, minval=1, maxval=12)
start_year = input(title="Start Year", type=input.integer, defval=2020)
end_date = input(title="End Date", type=input.integer, defval=6, minval=1, maxval=31)
end_month = input(title="End Month", type=input.integer, defval=9, minval=1, maxval=12)
end_year = input(title="End Year", type=input.integer, defval=2020)

between_dates = (time >= timestamp(start_year, start_month, start_date, 7, 0)) and (time < timestamp(end_year, end_month, end_date, 23, 59))

if between_dates
    strategy.entry("doge door", strategy.long, when=buy_condition)
